import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Link, NavLink, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bot, BrainCircuit, ChevronRight, FileUp, FolderOpen, LoaderCircle, LogOut, MessageSquare, Moon, Pencil, Plus, Send, Settings, Square, Sun, Trash2, Wrench } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { ConfirmButton, Empty, ErrorNotice, Form, Modal } from "./components";
import { api } from "./lib/api";
import { useAuth } from "./lib/auth";
import { streamMessage } from "./lib/sse";
import type { AgentSession, ChatMessage, ProviderModel, SseEvent, Workspace } from "./lib/types";
import { Workbench } from "./Workbench";

function queryKeys() { return { workspaces: ["workspaces"] as const, sessions: ["sessions"] as const, profiles: ["profiles"] as const, bindings: ["bindings"] as const }; }

function ThemeButton() {
  const [theme, setTheme] = useState(() => localStorage.getItem("pi-saas.theme") ?? "system");
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("pi-saas.theme", theme); }, [theme]);
  return <button className="btn p-2" title="切换主题" onClick={() => setTheme(theme === "system" ? "light" : theme === "light" ? "dark" : "system")}>
    {theme === "dark" ? <Moon size={16} /> : <Sun size={16} />}<span className="hidden sm:inline">主题</span>
  </button>;
}

function Protected({ children }: { children: React.ReactNode }) {
  const { ready, user } = useAuth();
  if (!ready) return <div className="grid min-h-screen place-items-center"><LoaderCircle className="animate-spin" /></div>;
  return user ? <>{children}</> : <Navigate to="/login" replace />;
}

export function Shell({ children }: { children: ReactNode }) {
  const { user, signOut } = useAuth();
  const links = [["/chat", "聊天", MessageSquare], ["/knowledge", "知识库", BrainCircuit], ["/files", "工作区文件", FolderOpen], ["/settings", "设置", Settings]] as const;
  return <div className="app-shell min-h-screen bg-slate-950 text-slate-100">
    <header className="sticky top-0 z-30 flex h-14 items-center justify-between border-b border-slate-800 bg-slate-950/90 px-4 backdrop-blur">
      <Link to="/chat" className="flex items-center gap-2 font-semibold"><Bot className="text-sky-400" />Pi SaaS 工作台</Link>
      <div className="flex items-center gap-2"><span className="hidden text-sm muted md:inline">{user?.email}</span><ThemeButton /><button className="btn p-2" title="退出登录" onClick={signOut}><LogOut size={16} /></button></div>
    </header>
    <div className="mx-auto flex max-w-[1720px] gap-4 p-3 md:p-4">
      <nav className="sticky top-18 hidden h-fit w-44 shrink-0 space-y-1 md:block">{links.map(([to, label, Icon]) => <NavLink key={to} to={to} className={({ isActive }) => `flex items-center gap-2 rounded-md px-3 py-2 text-sm ${isActive ? "bg-sky-500/15 text-sky-300" : "muted hover:bg-slate-800 hover:text-slate-100"}`}><Icon size={16} />{label}</NavLink>)}</nav>
      <main className="min-w-0 flex-1">{children}</main>
    </div>
    <nav className="fixed inset-x-0 bottom-0 z-30 flex justify-around border-t border-slate-800 bg-slate-950 p-2 md:hidden">{links.map(([to, label, Icon]) => <NavLink key={to} to={to} className={({ isActive }) => `flex flex-col items-center gap-1 text-xs ${isActive ? "text-sky-300" : "muted"}`}><Icon size={18} />{label}</NavLink>)}</nav>
  </div>;
}

function LoginPage({ register = false }: { register?: boolean }) {
  const { user, signIn } = useAuth(); const navigate = useNavigate();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const mutation = useMutation({ mutationFn: () => signIn(email, password, register), onSuccess: () => navigate("/chat") });
  if (user) return <Navigate to="/chat" replace />;
  return <main className="grid min-h-screen place-items-center bg-slate-950 p-4"><section className="panel w-full max-w-md p-7">
    <Bot className="mb-4 text-sky-400" size={34} /><h1 className="text-2xl font-semibold">{register ? "创建 Pi SaaS 账号" : "登录 Pi SaaS"}</h1><p className="mt-2 text-sm muted">Agent、工作区与知识库都将按当前账号隔离。</p>
    <Form onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }}><label className="block text-sm">邮箱<input className="input mt-1" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="block text-sm">密码<input className="input mt-1" type="password" minLength={12} maxLength={256} required value={password} onChange={(event) => setPassword(event.target.value)} /><span className="mt-1 block text-xs muted">至少 12 个字符。</span></label><ErrorNotice error={mutation.error} /><button className="btn btn-primary w-full" disabled={mutation.isPending}>{mutation.isPending && <LoaderCircle className="animate-spin" size={16} />}{register ? "注册并进入工作台" : "登录"}</button></Form>
    <p className="mt-5 text-center text-sm muted">{register ? "已有账号？" : "没有账号？"}<Link className="ml-1 text-sky-300 underline" to={register ? "/login" : "/register"}>{register ? "去登录" : "去注册"}</Link></p>
  </section></main>;
}

function WorkspaceSelect({ workspaces, selected, onChange }: { workspaces: Workspace[]; selected: string | undefined; onChange: (id: string) => void }) {
  return <select aria-label="选择工作区" className="input max-w-48 py-2 text-sm" value={selected ?? ""} onChange={(event) => onChange(event.target.value)}>{workspaces.map((workspace) => <option key={workspace.id} value={workspace.id}>{workspace.name}{workspace.is_current ? "（当前）" : ""}</option>)}</select>;
}

export function ChatPage() {
  const navigate = useNavigate(); const { sessionId } = useParams(); const qc = useQueryClient(); const keys = queryKeys();
  const [newOpen, setNewOpen] = useState(false); const [renameOpen, setRenameOpen] = useState(false); const [pending, setPending] = useState<{ content: string; response: string; tools: SseEvent[] } | null>(null); const [streamError, setStreamError] = useState<unknown>(null);
  const workspacesQuery = useQuery({ queryKey: keys.workspaces, queryFn: api.workspaces });
  const workspaces = workspacesQuery.data?.items ?? []; const currentWorkspace = workspaces.find((item) => item.is_current) ?? workspaces[0];
  const sessionsQuery = useQuery({ queryKey: keys.sessions, queryFn: api.sessions }); const sessions = sessionsQuery.data?.items ?? [];
  const sessionQuery = useQuery({ queryKey: ["session", sessionId], queryFn: () => api.session(sessionId!), enabled: Boolean(sessionId), refetchInterval: (query) => query.state.data?.latest_run?.status === "running" ? 2_000 : false });
  const messageQuery = useQuery({ queryKey: ["messages", sessionId], queryFn: () => api.messages(sessionId!), enabled: Boolean(sessionId) });
  const selected = sessionQuery.data ?? sessions.find((item) => item.id === sessionId);
  const profilesQuery = useQuery({ queryKey: keys.profiles, queryFn: api.profiles });
  const knowledgeQuery = useQuery({ queryKey: ["knowledge-bases", currentWorkspace?.id], queryFn: () => api.knowledgeBases(currentWorkspace!.id), enabled: Boolean(currentWorkspace) });
  const refreshSessions = () => void qc.invalidateQueries({ queryKey: keys.sessions });
  const switchWorkspace = useMutation({ mutationFn: api.switchWorkspace, onSuccess: () => { void qc.invalidateQueries({ queryKey: keys.workspaces }); navigate("/chat"); } });
  const deleteSession = useMutation({ mutationFn: api.deleteSession, onSuccess: () => { refreshSessions(); navigate("/chat"); } });
  const messages = messageQuery.data?.items ?? [];
  const submit = async (content: string) => {
    if (!selected || pending) return;
    setStreamError(null); setPending({ content, response: "", tools: [] });
    try {
      await streamMessage(selected.id, content, (event) => {
        if (event.name === "assistant.delta") setPending((value) => value ? { ...value, response: `${value.response}${String(event.data.delta ?? "")}` } : value);
        if (event.name.startsWith("tool.")) setPending((value) => value ? { ...value, tools: [...value.tools, event] } : value);
        if (event.name === "message.accepted" && !selected.title) {
          const title = content.replace(/\s+/g, " ").trim().slice(0, 40);
          if (title) void api.updateSessionTitle(selected.id, title).then(refreshSessions).catch(() => undefined);
        }
      });
    } catch (error) { setStreamError(error); }
    finally { setPending(null); void qc.invalidateQueries({ queryKey: ["messages", selected.id] }); void qc.invalidateQueries({ queryKey: ["session", selected.id] }); refreshSessions(); }
  };
  return <Shell><div className="grid min-h-[calc(100vh-6rem)] grid-cols-1 gap-3 lg:grid-cols-[260px_minmax(0,1fr)_260px]">
    <aside className="panel hidden overflow-auto p-3 lg:block"><div className="mb-3 flex items-center justify-between"><span className="font-medium">会话</span><button className="btn btn-primary p-2" title="新建会话" onClick={() => setNewOpen(true)}><Plus size={16} /></button></div><div className="space-y-1">{sessions.filter((item) => !currentWorkspace || item.workspace_id === currentWorkspace.id).map((item) => <button key={item.id} onClick={() => navigate(`/chat/${item.id}`)} className={`w-full rounded-md px-3 py-2 text-left text-sm ${item.id === sessionId ? "bg-sky-500/15 text-sky-200" : "hover:bg-slate-800"}`}><div className="truncate">{item.title ?? "新会话"}</div><div className="mt-1 text-xs muted">{item.latest_run?.status === "running" ? "正在执行" : item.knowledge_base_ids.length ? `${item.knowledge_base_ids.length} 个知识库` : "无知识库"}</div></button>)}{sessions.length === 0 && <p className="p-3 text-sm muted">还没有会话。</p>}</div></aside>
    <section className="panel flex min-h-[72vh] min-w-0 flex-col overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800 p-3"><div className="flex min-w-0 items-center gap-2"><WorkspaceSelect workspaces={workspaces} selected={currentWorkspace?.id} onChange={(id) => switchWorkspace.mutate(id)} /><ChevronRight className="muted" size={16} /><span className="truncate font-medium">{selected?.title ?? (selected ? "新会话" : "选择或创建会话")}</span>{selected?.latest_run?.status === "running" && <span className="badge bg-amber-500/15 text-amber-200">运行中</span>}</div>{selected && <div className="flex gap-2"><button className="btn p-2" title="重命名" onClick={() => setRenameOpen(true)}><Pencil size={15} /></button><ConfirmButton label={<Trash2 size={15} />} confirmText="确认删除" onConfirm={() => deleteSession.mutate(selected.id)} /></div>}</header>
      <div className="scrollbar flex-1 space-y-4 overflow-auto p-4">{!selected ? <Empty><div><p>从左侧选择一个会话，或新建会话开始。</p><button className="btn btn-primary mt-3" onClick={() => setNewOpen(true)}><Plus size={16} />新建会话</button></div></Empty> : <><ErrorNotice error={messageQuery.error ?? streamError ?? deleteSession.error} />{messages.map((message) => <MessageBubble key={message.id} message={message} />)}{pending && <PendingMessage value={pending} />}</>}</div>
      {selected && <Composer disabled={Boolean(pending) || selected.latest_run?.status === "running"} running={selected.latest_run?.status === "running"} onSend={submit} onAbort={() => void api.controlSession(selected.id, "abort")} onSteer={(content) => void api.controlSession(selected.id, "steer", content)} onFollowUp={(content) => void api.controlSession(selected.id, "follow-up", content)} />}
    </section>
    <aside className="panel hidden overflow-auto p-4 lg:block"><h2 className="font-medium">会话上下文</h2>{selected ? <div className="mt-4 space-y-4 text-sm"><div><p className="muted">Profile</p><p className="mt-1 break-all">{profilesQuery.data?.items.find((profile) => profile.id === selected.profile_id)?.name ?? selected.profile_id}</p></div><div><p className="muted">绑定知识库</p>{selected.knowledge_base_ids.length ? <ul className="mt-1 space-y-1">{selected.knowledge_base_ids.map((id) => <li key={id} className="break-all text-xs">{knowledgeQuery.data?.items.find((item) => item.id === id)?.name ?? id}</li>)}</ul> : <p className="mt-1 muted">未绑定</p>}</div><p className="rounded bg-slate-800/70 p-2 text-xs muted">知识库绑定在创建会话后不可修改；需要变更时请新建会话。</p></div> : <p className="mt-3 text-sm muted">会话运行状态与 RAG 工具引用会在这里显示。</p>}</aside>
  </div><NewSessionModal open={newOpen} onClose={() => setNewOpen(false)} workspaces={workspaces} profiles={profilesQuery.data?.items ?? []} currentWorkspace={currentWorkspace} onCreated={(id) => { setNewOpen(false); refreshSessions(); navigate(`/chat/${id}`); }} /><RenameModal open={renameOpen} onClose={() => setRenameOpen(false)} session={selected} onSaved={() => { setRenameOpen(false); refreshSessions(); void qc.invalidateQueries({ queryKey: ["session", sessionId] }); }} /></Shell>;
}

function MessageBubble({ message }: { message: ChatMessage }) {
  if (message.role === "tool_call" || message.role === "tool_result") return <details className="rounded-md border border-slate-700 bg-slate-900/60 p-3 text-sm"><summary className="cursor-pointer text-sky-200"><Wrench className="mr-1 inline" size={14} />{message.tool_name ?? message.content}{message.is_error ? "（失败）" : ""}</summary><pre className="mt-3 max-h-64 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(message.role === "tool_call" ? message.arguments : message.result, null, 2)}</pre>{message.payload_truncated && <p className="mt-2 text-xs text-amber-300">工具载荷已截断。</p>}</details>;
  const user = message.role === "user";
  return <article className={`flex ${user ? "justify-end" : "justify-start"}`}><div className={`max-w-[88%] rounded-xl px-4 py-3 text-sm ${user ? "bg-sky-700 text-white" : "bg-slate-800"}`}><p className="mb-2 text-xs opacity-70">{user ? "你" : "Agent"}</p>{user ? <p className="whitespace-pre-wrap">{message.content}</p> : <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{message.content}</ReactMarkdown></div>}</div></article>;
}

function PendingMessage({ value }: { value: { content: string; response: string; tools: SseEvent[] } }) { return <><article className="flex justify-end"><div className="max-w-[88%] rounded-xl bg-sky-700 px-4 py-3 text-sm text-white">{value.content}</div></article>{value.tools.map((event, index) => <details key={`${event.name}-${index}`} open className="rounded-md border border-sky-800/60 bg-sky-950/30 p-3 text-sm"><summary>{event.name === "tool.started" ? "正在调用" : "已完成"} {String(event.data.toolName ?? event.data.tool ?? "工具")}</summary><pre className="mt-2 overflow-auto text-xs">{JSON.stringify(event.data, null, 2)}</pre></details>)}<article className="flex justify-start"><div className="max-w-[88%] rounded-xl bg-slate-800 px-4 py-3 text-sm"><div className="markdown">{value.response ? <ReactMarkdown remarkPlugins={[remarkGfm]}>{value.response}</ReactMarkdown> : <span className="flex items-center gap-2 muted"><LoaderCircle size={15} className="animate-spin" />Agent 正在思考…</span>}</div></div></article></>; }

function Composer({ disabled, running, onSend, onAbort, onSteer, onFollowUp }: { disabled: boolean; running: boolean; onSend: (content: string) => void; onAbort: () => void; onSteer: (content: string) => void; onFollowUp: (content: string) => void }) {
  const [content, setContent] = useState(""); const submit = (event: FormEvent) => { event.preventDefault(); const text = content.trim(); if (!text) return; if (running) onSteer(text); else { onSend(text); setContent(""); } };
  return <form className="border-t border-slate-800 p-3" onSubmit={submit}><div className="flex gap-2"><textarea className="input min-h-12 resize-y" placeholder={running ? "向正在执行的任务追加引导…" : "输入任务或问题…"} value={content} onChange={(event) => setContent(event.target.value)} disabled={disabled && !running} /><div className="flex flex-col gap-2">{running && <><button type="button" className="btn p-2" title="作为 follow-up 追加" disabled={!content.trim()} onClick={() => { onFollowUp(content.trim()); setContent(""); }}><MessageSquare size={16} /></button><button type="button" className="btn btn-danger p-2" title="中止" onClick={onAbort}><Square size={16} /></button></>}<button className="btn btn-primary p-2" disabled={!content.trim() || (disabled && !running)} title={running ? "追加引导" : "发送"}><Send size={16} /></button></div></div></form>;
}

function NewSessionModal({ open, onClose, workspaces, profiles, currentWorkspace, onCreated }: { open: boolean; onClose: () => void; workspaces: Workspace[]; profiles: Array<{ id: string; name: string }>; currentWorkspace?: Workspace; onCreated: (id: string) => void }) {
  const [workspaceId, setWorkspaceId] = useState(""); const [profileId, setProfileId] = useState(""); const [knowledgeBaseIds, setKnowledgeBaseIds] = useState<string[]>([]);
  useEffect(() => { if (open && currentWorkspace) setWorkspaceId(currentWorkspace.id); }, [open, currentWorkspace]);
  const kbs = useQuery({ queryKey: ["knowledge-bases", workspaceId], queryFn: () => api.knowledgeBases(workspaceId), enabled: Boolean(workspaceId) });
  const mutation = useMutation({ mutationFn: () => api.createSession({ workspace_id: workspaceId, profile_id: profileId, knowledge_base_ids: knowledgeBaseIds }), onSuccess: (session) => onCreated(session.id) });
  const toggle = (id: string) => setKnowledgeBaseIds((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length >= 20 ? current : [...current, id]);
  return <Modal open={open} title="新建 Agent 会话" onClose={onClose}><Form onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }}><label className="block text-sm">工作区<select className="input mt-1" value={workspaceId} onChange={(event) => { setWorkspaceId(event.target.value); setKnowledgeBaseIds([]); }}>{workspaces.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-sm">Agent Profile<select className="input mt-1" required value={profileId} onChange={(event) => setProfileId(event.target.value)}><option value="">请选择</option>{profiles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{profiles.length === 0 && <p className="text-sm text-amber-300">请先在设置中配置 Provider 与 Profile。</p>}<fieldset><legend className="text-sm">绑定知识库（可选，最多 20 个）</legend><p className="mt-1 text-xs muted">绑定后不可修改；Agent 仅能通过 rag_search 查询这里的知识库。</p><div className="mt-2 max-h-40 space-y-1 overflow-auto">{kbs.data?.items.filter((item) => item.status === "active").map((item) => <label key={item.id} className="flex items-center gap-2 rounded p-2 hover:bg-slate-800"><input type="checkbox" checked={knowledgeBaseIds.includes(item.id)} onChange={() => toggle(item.id)} />{item.name}<span className="ml-auto text-xs muted">{item.vector_backend}</span></label>)}{kbs.data?.items.length === 0 && <p className="text-sm muted">当前工作区尚无可用知识库。</p>}</div></fieldset><ErrorNotice error={mutation.error} /><button className="btn btn-primary w-full" disabled={!workspaceId || !profileId || mutation.isPending}>{mutation.isPending && <LoaderCircle className="animate-spin" size={16} />}创建会话</button></Form></Modal>;
}

function RenameModal({ open, onClose, session, onSaved }: { open: boolean; onClose: () => void; session?: AgentSession; onSaved: () => void }) { const [title, setTitle] = useState(""); useEffect(() => setTitle(session?.title ?? ""), [session]); const mutation = useMutation({ mutationFn: () => api.updateSessionTitle(session!.id, title), onSuccess: onSaved }); return <Modal open={open} title="重命名会话" onClose={onClose}><Form onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }}><input className="input" maxLength={256} autoFocus value={title} onChange={(event) => setTitle(event.target.value)} /><ErrorNotice error={mutation.error} /><button className="btn btn-primary w-full" disabled={!title.trim() || mutation.isPending}>保存</button></Form></Modal>; }

export function FilesPage() { const qc = useQueryClient(); const [path, setPath] = useState(""); const [file, setFile] = useState<File | null>(null); const workspaces = useQuery({ queryKey: ["workspaces"], queryFn: api.workspaces }); const [workspaceId, setWorkspaceId] = useState(""); useEffect(() => { if (!workspaceId && workspaces.data?.items[0]) setWorkspaceId(workspaces.data.items.find((item) => item.is_current)?.id ?? workspaces.data.items[0].id); }, [workspaceId, workspaces.data]); const files = useQuery({ queryKey: ["workspace-files", workspaceId], queryFn: () => api.workspaceFiles(workspaceId), enabled: Boolean(workspaceId) }); const upload = useMutation({ mutationFn: () => api.uploadWorkspaceFile(workspaceId, path || file?.name || "", file!, false), onSuccess: () => { setFile(null); setPath(""); void qc.invalidateQueries({ queryKey: ["workspace-files", workspaceId] }); } }); const remove = useMutation({ mutationFn: (target: string) => api.deleteWorkspaceFile(workspaceId, target), onSuccess: () => void qc.invalidateQueries({ queryKey: ["workspace-files", workspaceId] }) }); return <Shell><section className="space-y-4"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">工作区文件</h1><p className="mt-1 text-sm muted">这些文件供 Agent 在对应 Workspace 中读取和修改。</p></div><WorkspaceSelect workspaces={workspaces.data?.items ?? []} selected={workspaceId} onChange={setWorkspaceId} /></header><section className="panel p-4"><Form onSubmit={(event) => { event.preventDefault(); if (file) upload.mutate(); }}><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">选择文件<input className="input mt-1" type="file" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label><label className="text-sm">目标相对路径（默认文件名）<input className="input mt-1" value={path} onChange={(event) => setPath(event.target.value)} placeholder="src/notes.md" /></label></div><ErrorNotice error={upload.error} /><button className="btn btn-primary" disabled={!file || upload.isPending}><FileUp size={16} />上传</button></Form></section><section className="panel overflow-hidden"><div className="border-b border-slate-800 p-4 font-medium">文件列表</div>{files.isLoading ? <div className="p-6"><LoaderCircle className="animate-spin" /></div> : files.data?.items.length ? <ul>{files.data.items.map((item) => <li key={item.path} className="flex items-center gap-3 border-b border-slate-800 px-4 py-3 text-sm last:border-0"><span className="min-w-0 flex-1 break-all">{item.path}</span><span className="text-xs muted">{item.size_bytes.toLocaleString()} B</span><ConfirmButton label={<Trash2 size={15} />} confirmText="确认" onConfirm={() => remove.mutate(item.path)} /></li>)}</ul> : <Empty>当前工作区没有文件。</Empty>}</section></section></Shell>; }

export function SettingsPage() {
  const qc = useQueryClient();
  const [bindingOpen, setBindingOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  const [editingProfile, setEditingProfile] = useState<{ id: string; name: string; model_id: string; thinking_level: string | null }>();
  const bindings = useQuery({ queryKey: ["bindings"], queryFn: api.bindings });
  const profiles = useQuery({ queryKey: ["profiles"], queryFn: api.profiles });
  const runtime = useQuery({ queryKey: ["runtime"], queryFn: api.runtime });
  const removeBinding = useMutation({ mutationFn: api.deleteBinding, onSuccess: () => void qc.invalidateQueries({ queryKey: ["bindings"] }) });
  const removeProfile = useMutation({ mutationFn: api.deleteProfile, onSuccess: () => void qc.invalidateQueries({ queryKey: ["profiles"] }) });
  const recovery = useMutation({ mutationFn: api.recreateRuntime, onSuccess: () => void qc.invalidateQueries({ queryKey: ["runtime"] }) });
  const closeProfile = () => { setProfileOpen(false); setEditingProfile(undefined); };
  return <Shell><section className="space-y-5"><header><h1 className="text-xl font-semibold">设置与模型</h1><p className="mt-1 text-sm muted">密钥仅在提交时传给 Gateway，读取接口不会返回密钥。</p></header>
    <section className="panel p-4"><div className="flex items-center justify-between"><div><h2 className="font-medium">Runtime</h2><p className="mt-1 text-sm muted">{runtime.data?.state ?? "正在读取状态"}{runtime.data?.last_error ? ` · ${runtime.data.last_error}` : ""}</p></div><div className="flex gap-2"><button className="btn" onClick={() => void api.startRuntime().then(() => qc.invalidateQueries({ queryKey: ["runtime"] }))}>启动</button><button className="btn" onClick={() => recovery.mutate()} disabled={recovery.isPending}>重建</button></div></div><ErrorNotice error={runtime.error ?? recovery.error} /></section>
    <section className="panel overflow-hidden"><header className="flex items-center justify-between border-b border-slate-800 p-4"><div><h2 className="font-medium">Provider Bindings</h2><p className="mt-1 text-sm muted">一个 Binding 对应一个 Provider 凭据。</p></div><button className="btn btn-primary" onClick={() => setBindingOpen(true)}><Plus size={16} />添加</button></header>{bindings.data?.items.length ? <ul>{bindings.data.items.map((item) => <li className="flex items-center gap-3 border-b border-slate-800 p-4 last:border-0" key={item.id}><div className="min-w-0 flex-1"><p>{item.display_name}</p><p className="text-xs muted">{item.provider_id} · {item.status}</p></div><ConfirmButton label={<Trash2 size={15} />} confirmText="确认禁用" onConfirm={() => removeBinding.mutate(item.id)} /></li>)}</ul> : <Empty>尚未配置 Provider。</Empty>}<ErrorNotice error={bindings.error ?? removeBinding.error} /></section>
    <section className="panel overflow-hidden"><header className="flex items-center justify-between border-b border-slate-800 p-4"><div><h2 className="font-medium">Agent Profiles</h2><p className="mt-1 text-sm muted">Profile 决定新会话使用的模型与思考级别。</p></div><button className="btn btn-primary" onClick={() => { setEditingProfile(undefined); setProfileOpen(true); }}><Plus size={16} />创建</button></header>{profiles.data?.items.length ? <ul>{profiles.data.items.map((item) => <li className="flex items-center gap-3 border-b border-slate-800 p-4 last:border-0" key={item.id}><div className="min-w-0 flex-1"><p>{item.name}</p><p className="text-xs muted">{item.model_id}{item.thinking_level ? ` · ${item.thinking_level}` : ""}</p></div><button className="btn p-2" title="更新 Profile" onClick={() => { setEditingProfile(item); setProfileOpen(true); }}><Pencil size={15} /></button><ConfirmButton label={<Trash2 size={15} />} confirmText="确认删除" onConfirm={() => removeProfile.mutate(item.id)} /></li>)}</ul> : <Empty>请先创建 Profile，然后才能新建 Agent 会话。</Empty>}<ErrorNotice error={profiles.error ?? removeProfile.error} /></section>
  </section><BindingModal open={bindingOpen} onClose={() => setBindingOpen(false)} onSaved={() => { setBindingOpen(false); void qc.invalidateQueries({ queryKey: ["bindings"] }); }} /><ProfileModal open={profileOpen} onClose={closeProfile} bindings={bindings.data?.items ?? []} profile={editingProfile} onSaved={() => { closeProfile(); void qc.invalidateQueries({ queryKey: ["profiles"] }); }} /></Shell>;
}

function BindingModal({ open, onClose, onSaved }: { open: boolean; onClose: () => void; onSaved: () => void }) { const providers = useQuery({ queryKey: ["providers"], queryFn: api.providers, enabled: open }); const [providerId, setProviderId] = useState(""); const [name, setName] = useState(""); const [apiKey, setApiKey] = useState(""); const mutation = useMutation({ mutationFn: () => api.createBinding({ provider_id: providerId, display_name: name, api_key: apiKey }), onSuccess: onSaved }); return <Modal open={open} title="添加 Provider Binding" onClose={onClose}><Form onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }}><label className="block text-sm">Provider<select className="input mt-1" required value={providerId} onChange={(event) => setProviderId(event.target.value)}><option value="">请选择</option>{providers.data?.providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.name} ({provider.id})</option>)}</select></label><label className="block text-sm">显示名称<input className="input mt-1" required value={name} onChange={(event) => setName(event.target.value)} /></label><label className="block text-sm">API Key<input className="input mt-1" type="password" required autoComplete="off" value={apiKey} onChange={(event) => setApiKey(event.target.value)} /></label><ErrorNotice error={providers.error ?? mutation.error} /><button className="btn btn-primary w-full" disabled={!providerId || mutation.isPending}>安全保存 Binding</button></Form></Modal>; }

function ProfileModal({ open, onClose, bindings, profile, onSaved }: { open: boolean; onClose: () => void; bindings: Array<{ id: string; display_name: string }>; profile?: { id: string; name: string; model_id: string; thinking_level: string | null }; onSaved: () => void }) {
  const [bindingId, setBindingId] = useState(""); const [name, setName] = useState(""); const [modelId, setModelId] = useState(""); const [thinking, setThinking] = useState("");
  useEffect(() => { if (open) { setBindingId(""); setName(profile?.name ?? ""); setModelId(""); setThinking(profile?.thinking_level ?? ""); } }, [open, profile]);
  const models = useQuery({ queryKey: ["binding-models", bindingId], queryFn: () => api.bindingModels(bindingId), enabled: Boolean(bindingId) && open });
  const mutation = useMutation({ mutationFn: () => { const body = { name, provider_binding_id: bindingId, model_id: modelId, thinking_level: thinking || null }; return profile ? api.updateProfile(profile.id, body) : api.createProfile(body); }, onSuccess: onSaved });
  const chosen = models.data?.models.find((item) => item.id === modelId);
  return <Modal open={open} title={profile ? "更新 Agent Profile" : "创建 Agent Profile"} onClose={onClose}><Form onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }}><p className="rounded bg-slate-800/60 p-2 text-xs muted">{profile ? "读取接口不会返回原 Binding；更新时请重新选择可用 Binding 和模型。" : "Profile 用于创建新的 Agent 会话。"}</p><label className="block text-sm">Binding<select className="input mt-1" required value={bindingId} onChange={(event) => { setBindingId(event.target.value); setModelId(""); setThinking(""); }}><option value="">请选择</option>{bindings.map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label><label className="block text-sm">模型<select className="input mt-1" required value={modelId} onChange={(event) => { setModelId(event.target.value); setThinking(""); }}><option value="">请选择</option>{models.data?.models.map((item: ProviderModel) => <option key={item.id} value={item.id}>{item.name} ({item.id})</option>)}</select></label><label className="block text-sm">思考级别<select className="input mt-1" value={thinking} onChange={(event) => setThinking(event.target.value)}><option value="">默认</option>{chosen?.thinking_levels.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="block text-sm">Profile 名称<input className="input mt-1" required value={name} onChange={(event) => setName(event.target.value)} /></label><ErrorNotice error={models.error ?? mutation.error} /><button className="btn btn-primary w-full" disabled={!name || !modelId || mutation.isPending}>{profile ? "更新 Profile" : "创建 Profile"}</button></Form></Modal>;
}

export function App() { const workbench = <Protected><Workbench /></Protected>; return <Routes><Route path="/login" element={<LoginPage />} /><Route path="/register" element={<LoginPage register />} /><Route path="/chat" element={workbench} /><Route path="/chat/:sessionId" element={workbench} /><Route path="/knowledge" element={workbench} /><Route path="/knowledge/:knowledgeBaseId" element={workbench} /><Route path="/files" element={workbench} /><Route path="/settings" element={workbench} /><Route path="*" element={<Navigate to="/chat" replace />} /></Routes>; }
